### ISSUE TITLE
Thank you for your excellent work. Doesn’t SRCNN need to interpolate low-resolution images and input them into the network? Why didn’t you change the image size here, please help me, my dears

### ISSUE THREAD

**Issue by Brightlcz** [yjn870/SRCNN-pytorch#11]
https://github.com/yjn870/SRCNN-pytorch/blob/064dbaac09859f5fa1b35608ab90145e2d60828b/test.py#L35

**Comment by andronius-yang** [comment]
image_width is the image width of the final output HR image.
The // operator is floor division, i.e. it rounds down the float result of division into an integer.
For example, if you wish to test your 3x resolution algorithm on a 512 * 512 image, the algorithm first has to down-scale it to 1/3 of its resolution. 512/3 = 170.666..., and there can't be fractional pixels. Hence, 512//3 gives 170 pixels, your LR image will then have resolution of 170*170. Lastly, your output HR image will have width 170*3, which is 510 pixels. So in essence, the algorithm will take in an image of resolution 170*170 and output resolution 510*510.

**Comment by Brightlcz** [comment]
> image_width is the image width of the final output HR image.
> The // operator is floor division, i.e. it rounds down the float result of division into an integer.
> For example, if you wish to test your 3x resolution algorithm on a 512 * 512 image, the algorithm first has to down-scale it to 1/3 of its resolution. 512/3 = 170.666..., and there can't be fractional pixels. Hence, 512//3 gives 170 pixels, your LR image will then have resolution of 170_170. Lastly, your output HR image will have width 170_3, which is 510 pixels. So in essence, the algorithm will take in an image of resolution 170_170 and output resolution 510_510.



> image_width is the image width of the final output HR image.
> The // operator is floor division, i.e. it rounds down the float result of division into an integer.
> For example, if you wish to test your 3x resolution algorithm on a 512 * 512 image, the algorithm first has to down-scale it to 1/3 of its resolution. 512/3 = 170.666..., and there can't be fractional pixels. Hence, 512//3 gives 170 pixels, your LR image will then have resolution of 170_170. Lastly, your output HR image will have width 170_3, which is 510 pixels. So in essence, the algorithm will take in an image of resolution 170_170 and output resolution 510_510.

谢谢您，那37，38，38行目的是在做什么工作呢？

**Comment by andronius-yang** [comment]
37行 image = image.resize((image_width, image_height), resample=pil_image.BICUBIC)
这一行具体做的就是把源文件先做一个bicubic filter，并不会upscale或者downscale。我对比了加和不加这行的结果分别是图片的最外围会更亮一些，目的我估计是先加zero-padding，但具体我也不是很清楚。（zero-padding就是给整个图片最外围加一圈的黑色的像素）
38行 image = image.resize((image.width // args.scale, image.height // args.scale), resample=pil_image.BICUBIC)
这行resize就是用到之前向下取整的除法来获得低分辨率的图像（low resolution image），后面的resample=pil_image.BICUBIC就是说要用bicubic filter来进行降低分辨率
39行 image = image.resize((image.width * args.scale, image.height * args.scale), resample=pil_image.BICUBIC)
这行也困扰了我挺久的。这行做的就是把原来的低分辨率图像再重新通过bicubic interpolation变回高分辨率图像。当时我想的是既然SRCNN目的是为了通过CNN来达成upscale目的，那为什么还要通过bicubic interpolation来upscale呢？
之后看下原论文 https://arxiv.org/pdf/1501.00092.pdf 里边才恍然大悟，第三页："Consider a single low-resolution image, we first upscale it to the desired size using bicubic interpolation, which is the only pre-processing we perform." 具体意思就是SRCNN真正算法是先将低分辨率图像通过bicubic interpolation upscale到高分辨率，之后通过CNN来将这个模糊的“高分辨率图像”变成更加清晰的高分辨率图像。

**Comment by tongchangD** [comment]
你这个代码直接test 是没有将图像增大的，根本没有达到超分原图的效果
